// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/janknspank/proto/classifier.proto

package com.janknspank.proto;

public final class ClassifierProto {
  private ClassifierProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FeatureBenchmarkOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 feature_id = 1;
    /**
     * <code>optional int64 feature_id = 1;</code>
     *
     * <pre>
     * A name for this person.  Not really used for much of anything now,
     * but helpful to keep in mind who our different personas are so we can
     * talk about them.
     * </pre>
     */
    boolean hasFeatureId();
    /**
     * <code>optional int64 feature_id = 1;</code>
     *
     * <pre>
     * A name for this person.  Not really used for much of anything now,
     * but helpful to keep in mind who our different personas are so we can
     * talk about them.
     * </pre>
     */
    long getFeatureId();

    // optional string email = 2;
    /**
     * <code>optional string email = 2;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 2;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 2;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // repeated string good_url = 3;
    /**
     * <code>repeated string good_url = 3;</code>
     */
    java.util.List<java.lang.String>
    getGoodUrlList();
    /**
     * <code>repeated string good_url = 3;</code>
     */
    int getGoodUrlCount();
    /**
     * <code>repeated string good_url = 3;</code>
     */
    java.lang.String getGoodUrl(int index);
    /**
     * <code>repeated string good_url = 3;</code>
     */
    com.google.protobuf.ByteString
        getGoodUrlBytes(int index);

    // repeated string bad_url = 4;
    /**
     * <code>repeated string bad_url = 4;</code>
     */
    java.util.List<java.lang.String>
    getBadUrlList();
    /**
     * <code>repeated string bad_url = 4;</code>
     */
    int getBadUrlCount();
    /**
     * <code>repeated string bad_url = 4;</code>
     */
    java.lang.String getBadUrl(int index);
    /**
     * <code>repeated string bad_url = 4;</code>
     */
    com.google.protobuf.ByteString
        getBadUrlBytes(int index);
  }
  /**
   * Protobuf type {@code FeatureBenchmark}
   */
  public static final class FeatureBenchmark extends
      com.google.protobuf.GeneratedMessage
      implements FeatureBenchmarkOrBuilder {
    // Use FeatureBenchmark.newBuilder() to construct.
    private FeatureBenchmark(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FeatureBenchmark(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FeatureBenchmark defaultInstance;
    public static FeatureBenchmark getDefaultInstance() {
      return defaultInstance;
    }

    public FeatureBenchmark getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FeatureBenchmark(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              featureId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              email_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                goodUrl_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              goodUrl_.add(input.readBytes());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                badUrl_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              badUrl_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          goodUrl_ = new com.google.protobuf.UnmodifiableLazyStringList(goodUrl_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          badUrl_ = new com.google.protobuf.UnmodifiableLazyStringList(badUrl_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.janknspank.proto.ClassifierProto.internal_static_FeatureBenchmark_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.janknspank.proto.ClassifierProto.internal_static_FeatureBenchmark_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.janknspank.proto.ClassifierProto.FeatureBenchmark.class, com.janknspank.proto.ClassifierProto.FeatureBenchmark.Builder.class);
    }

    public static com.google.protobuf.Parser<FeatureBenchmark> PARSER =
        new com.google.protobuf.AbstractParser<FeatureBenchmark>() {
      public FeatureBenchmark parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FeatureBenchmark(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FeatureBenchmark> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 feature_id = 1;
    public static final int FEATURE_ID_FIELD_NUMBER = 1;
    private long featureId_;
    /**
     * <code>optional int64 feature_id = 1;</code>
     *
     * <pre>
     * A name for this person.  Not really used for much of anything now,
     * but helpful to keep in mind who our different personas are so we can
     * talk about them.
     * </pre>
     */
    public boolean hasFeatureId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 feature_id = 1;</code>
     *
     * <pre>
     * A name for this person.  Not really used for much of anything now,
     * but helpful to keep in mind who our different personas are so we can
     * talk about them.
     * </pre>
     */
    public long getFeatureId() {
      return featureId_;
    }

    // optional string email = 2;
    public static final int EMAIL_FIELD_NUMBER = 2;
    private java.lang.Object email_;
    /**
     * <code>optional string email = 2;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string email = 2;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string good_url = 3;
    public static final int GOOD_URL_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList goodUrl_;
    /**
     * <code>repeated string good_url = 3;</code>
     */
    public java.util.List<java.lang.String>
        getGoodUrlList() {
      return goodUrl_;
    }
    /**
     * <code>repeated string good_url = 3;</code>
     */
    public int getGoodUrlCount() {
      return goodUrl_.size();
    }
    /**
     * <code>repeated string good_url = 3;</code>
     */
    public java.lang.String getGoodUrl(int index) {
      return goodUrl_.get(index);
    }
    /**
     * <code>repeated string good_url = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGoodUrlBytes(int index) {
      return goodUrl_.getByteString(index);
    }

    // repeated string bad_url = 4;
    public static final int BAD_URL_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList badUrl_;
    /**
     * <code>repeated string bad_url = 4;</code>
     */
    public java.util.List<java.lang.String>
        getBadUrlList() {
      return badUrl_;
    }
    /**
     * <code>repeated string bad_url = 4;</code>
     */
    public int getBadUrlCount() {
      return badUrl_.size();
    }
    /**
     * <code>repeated string bad_url = 4;</code>
     */
    public java.lang.String getBadUrl(int index) {
      return badUrl_.get(index);
    }
    /**
     * <code>repeated string bad_url = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBadUrlBytes(int index) {
      return badUrl_.getByteString(index);
    }

    private void initFields() {
      featureId_ = 0L;
      email_ = "";
      goodUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      badUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, featureId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEmailBytes());
      }
      for (int i = 0; i < goodUrl_.size(); i++) {
        output.writeBytes(3, goodUrl_.getByteString(i));
      }
      for (int i = 0; i < badUrl_.size(); i++) {
        output.writeBytes(4, badUrl_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, featureId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEmailBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < goodUrl_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(goodUrl_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getGoodUrlList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < badUrl_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(badUrl_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getBadUrlList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.janknspank.proto.ClassifierProto.FeatureBenchmark parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.janknspank.proto.ClassifierProto.FeatureBenchmark parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.janknspank.proto.ClassifierProto.FeatureBenchmark parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.janknspank.proto.ClassifierProto.FeatureBenchmark parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.janknspank.proto.ClassifierProto.FeatureBenchmark parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.janknspank.proto.ClassifierProto.FeatureBenchmark parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.janknspank.proto.ClassifierProto.FeatureBenchmark parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.janknspank.proto.ClassifierProto.FeatureBenchmark parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.janknspank.proto.ClassifierProto.FeatureBenchmark parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.janknspank.proto.ClassifierProto.FeatureBenchmark parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.janknspank.proto.ClassifierProto.FeatureBenchmark prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FeatureBenchmark}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.janknspank.proto.ClassifierProto.FeatureBenchmarkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.janknspank.proto.ClassifierProto.internal_static_FeatureBenchmark_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.janknspank.proto.ClassifierProto.internal_static_FeatureBenchmark_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.janknspank.proto.ClassifierProto.FeatureBenchmark.class, com.janknspank.proto.ClassifierProto.FeatureBenchmark.Builder.class);
      }

      // Construct using com.janknspank.proto.ClassifierProto.FeatureBenchmark.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        featureId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        goodUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        badUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.janknspank.proto.ClassifierProto.internal_static_FeatureBenchmark_descriptor;
      }

      public com.janknspank.proto.ClassifierProto.FeatureBenchmark getDefaultInstanceForType() {
        return com.janknspank.proto.ClassifierProto.FeatureBenchmark.getDefaultInstance();
      }

      public com.janknspank.proto.ClassifierProto.FeatureBenchmark build() {
        com.janknspank.proto.ClassifierProto.FeatureBenchmark result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.janknspank.proto.ClassifierProto.FeatureBenchmark buildPartial() {
        com.janknspank.proto.ClassifierProto.FeatureBenchmark result = new com.janknspank.proto.ClassifierProto.FeatureBenchmark(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.featureId_ = featureId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.email_ = email_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          goodUrl_ = new com.google.protobuf.UnmodifiableLazyStringList(
              goodUrl_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.goodUrl_ = goodUrl_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          badUrl_ = new com.google.protobuf.UnmodifiableLazyStringList(
              badUrl_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.badUrl_ = badUrl_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.janknspank.proto.ClassifierProto.FeatureBenchmark) {
          return mergeFrom((com.janknspank.proto.ClassifierProto.FeatureBenchmark)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.janknspank.proto.ClassifierProto.FeatureBenchmark other) {
        if (other == com.janknspank.proto.ClassifierProto.FeatureBenchmark.getDefaultInstance()) return this;
        if (other.hasFeatureId()) {
          setFeatureId(other.getFeatureId());
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000002;
          email_ = other.email_;
          onChanged();
        }
        if (!other.goodUrl_.isEmpty()) {
          if (goodUrl_.isEmpty()) {
            goodUrl_ = other.goodUrl_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureGoodUrlIsMutable();
            goodUrl_.addAll(other.goodUrl_);
          }
          onChanged();
        }
        if (!other.badUrl_.isEmpty()) {
          if (badUrl_.isEmpty()) {
            badUrl_ = other.badUrl_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureBadUrlIsMutable();
            badUrl_.addAll(other.badUrl_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.janknspank.proto.ClassifierProto.FeatureBenchmark parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.janknspank.proto.ClassifierProto.FeatureBenchmark) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 feature_id = 1;
      private long featureId_ ;
      /**
       * <code>optional int64 feature_id = 1;</code>
       *
       * <pre>
       * A name for this person.  Not really used for much of anything now,
       * but helpful to keep in mind who our different personas are so we can
       * talk about them.
       * </pre>
       */
      public boolean hasFeatureId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 feature_id = 1;</code>
       *
       * <pre>
       * A name for this person.  Not really used for much of anything now,
       * but helpful to keep in mind who our different personas are so we can
       * talk about them.
       * </pre>
       */
      public long getFeatureId() {
        return featureId_;
      }
      /**
       * <code>optional int64 feature_id = 1;</code>
       *
       * <pre>
       * A name for this person.  Not really used for much of anything now,
       * but helpful to keep in mind who our different personas are so we can
       * talk about them.
       * </pre>
       */
      public Builder setFeatureId(long value) {
        bitField0_ |= 0x00000001;
        featureId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 feature_id = 1;</code>
       *
       * <pre>
       * A name for this person.  Not really used for much of anything now,
       * but helpful to keep in mind who our different personas are so we can
       * talk about them.
       * </pre>
       */
      public Builder clearFeatureId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        featureId_ = 0L;
        onChanged();
        return this;
      }

      // optional string email = 2;
      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 2;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        email_ = value;
        onChanged();
        return this;
      }

      // repeated string good_url = 3;
      private com.google.protobuf.LazyStringList goodUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureGoodUrlIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          goodUrl_ = new com.google.protobuf.LazyStringArrayList(goodUrl_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public java.util.List<java.lang.String>
          getGoodUrlList() {
        return java.util.Collections.unmodifiableList(goodUrl_);
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public int getGoodUrlCount() {
        return goodUrl_.size();
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public java.lang.String getGoodUrl(int index) {
        return goodUrl_.get(index);
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGoodUrlBytes(int index) {
        return goodUrl_.getByteString(index);
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public Builder setGoodUrl(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGoodUrlIsMutable();
        goodUrl_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public Builder addGoodUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGoodUrlIsMutable();
        goodUrl_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public Builder addAllGoodUrl(
          java.lang.Iterable<java.lang.String> values) {
        ensureGoodUrlIsMutable();
        super.addAll(values, goodUrl_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public Builder clearGoodUrl() {
        goodUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public Builder addGoodUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGoodUrlIsMutable();
        goodUrl_.add(value);
        onChanged();
        return this;
      }

      // repeated string bad_url = 4;
      private com.google.protobuf.LazyStringList badUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureBadUrlIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          badUrl_ = new com.google.protobuf.LazyStringArrayList(badUrl_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public java.util.List<java.lang.String>
          getBadUrlList() {
        return java.util.Collections.unmodifiableList(badUrl_);
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public int getBadUrlCount() {
        return badUrl_.size();
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public java.lang.String getBadUrl(int index) {
        return badUrl_.get(index);
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBadUrlBytes(int index) {
        return badUrl_.getByteString(index);
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public Builder setBadUrl(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBadUrlIsMutable();
        badUrl_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public Builder addBadUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBadUrlIsMutable();
        badUrl_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public Builder addAllBadUrl(
          java.lang.Iterable<java.lang.String> values) {
        ensureBadUrlIsMutable();
        super.addAll(values, badUrl_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public Builder clearBadUrl() {
        badUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public Builder addBadUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBadUrlIsMutable();
        badUrl_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FeatureBenchmark)
    }

    static {
      defaultInstance = new FeatureBenchmark(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:FeatureBenchmark)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FeatureBenchmark_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FeatureBenchmark_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%com/janknspank/proto/classifier.proto\032" +
      "(com/janknspank/database/extensions.prot" +
      "o\032\037com/janknspank/proto/user.proto\"w\n\020Fe" +
      "atureBenchmark\022\030\n\nfeature_id\030\001 \001(\003B\004\210\246\035\001" +
      "\022\030\n\005email\030\002 \001(\tB\t\210\246\035\001\230\246\035\377\005\022\027\n\010good_url\030\003" +
      " \003(\tB\005\230\246\035\377\005\022\026\n\007bad_url\030\004 \003(\tB\005\230\246\035\377\005B\'\n\024c" +
      "om.janknspank.protoB\017ClassifierProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_FeatureBenchmark_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_FeatureBenchmark_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FeatureBenchmark_descriptor,
              new java.lang.String[] { "FeatureId", "Email", "GoodUrl", "BadUrl", });
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registry.add(com.janknspank.database.ExtensionsProto.required);
          registry.add(com.janknspank.database.ExtensionsProto.required);
          registry.add(com.janknspank.database.ExtensionsProto.stringLength);
          registry.add(com.janknspank.database.ExtensionsProto.stringLength);
          registry.add(com.janknspank.database.ExtensionsProto.stringLength);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.janknspank.database.ExtensionsProto.getDescriptor(),
          com.janknspank.proto.UserProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
