// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/janknspank/proto/extensions.proto

package com.janknspank.proto;

public final class Extensions {
  private Extensions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.janknspank.proto.Extensions.required);
    registry.add(com.janknspank.proto.Extensions.storageMethod);
    registry.add(com.janknspank.proto.Extensions.stringLength);
    registry.add(com.janknspank.proto.Extensions.clientSerialization);
  }
  /**
   * Protobuf enum {@code Required}
   */
  public enum Required
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>YES = 1;</code>
     *
     * <pre>
     * This field must be set for its parent message to be valid.
     * </pre>
     */
    YES(0, 1),
    /**
     * <code>NO = 2;</code>
     *
     * <pre>
     * This field is optional.
     * </pre>
     */
    NO(1, 2),
    ;

    /**
     * <code>YES = 1;</code>
     *
     * <pre>
     * This field must be set for its parent message to be valid.
     * </pre>
     */
    public static final int YES_VALUE = 1;
    /**
     * <code>NO = 2;</code>
     *
     * <pre>
     * This field is optional.
     * </pre>
     */
    public static final int NO_VALUE = 2;


    public final int getNumber() { return value; }

    public static Required valueOf(int value) {
      switch (value) {
        case 1: return YES;
        case 2: return NO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Required>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Required>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Required>() {
            public Required findValueByNumber(int number) {
              return Required.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.janknspank.proto.Extensions.getDescriptor().getEnumTypes().get(0);
    }

    private static final Required[] VALUES = values();

    public static Required valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Required(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Required)
  }

  /**
   * Protobuf enum {@code StorageMethod}
   */
  public enum StorageMethod
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BLOB = 1;</code>
     *
     * <pre>
     * Default: Just throw this field into an opaque unindexed blob that will
     * be deserialized once we read it on the Java side.
     * </pre>
     */
    BLOB(0, 1),
    /**
     * <code>PRIMARY_KEY = 2;</code>
     *
     * <pre>
     * Use this field as the primary key.
     * </pre>
     */
    PRIMARY_KEY(1, 2),
    /**
     * <code>INDEX = 3;</code>
     *
     * <pre>
     * Pull out this field into its own row and put an index on it.
     * </pre>
     */
    INDEX(2, 3),
    /**
     * <code>UNIQUE_INDEX = 4;</code>
     *
     * <pre>
     * Pull out this field into its own row and put an unique index on it (that
     * is, all values in this column will be unique).
     * </pre>
     */
    UNIQUE_INDEX(3, 4),
    /**
     * <code>PULL_OUT = 5;</code>
     *
     * <pre>
     * Pull out this field into its own row in the MySQL schema, but do not
     * index it.
     * </pre>
     */
    PULL_OUT(4, 5),
    ;

    /**
     * <code>BLOB = 1;</code>
     *
     * <pre>
     * Default: Just throw this field into an opaque unindexed blob that will
     * be deserialized once we read it on the Java side.
     * </pre>
     */
    public static final int BLOB_VALUE = 1;
    /**
     * <code>PRIMARY_KEY = 2;</code>
     *
     * <pre>
     * Use this field as the primary key.
     * </pre>
     */
    public static final int PRIMARY_KEY_VALUE = 2;
    /**
     * <code>INDEX = 3;</code>
     *
     * <pre>
     * Pull out this field into its own row and put an index on it.
     * </pre>
     */
    public static final int INDEX_VALUE = 3;
    /**
     * <code>UNIQUE_INDEX = 4;</code>
     *
     * <pre>
     * Pull out this field into its own row and put an unique index on it (that
     * is, all values in this column will be unique).
     * </pre>
     */
    public static final int UNIQUE_INDEX_VALUE = 4;
    /**
     * <code>PULL_OUT = 5;</code>
     *
     * <pre>
     * Pull out this field into its own row in the MySQL schema, but do not
     * index it.
     * </pre>
     */
    public static final int PULL_OUT_VALUE = 5;


    public final int getNumber() { return value; }

    public static StorageMethod valueOf(int value) {
      switch (value) {
        case 1: return BLOB;
        case 2: return PRIMARY_KEY;
        case 3: return INDEX;
        case 4: return UNIQUE_INDEX;
        case 5: return PULL_OUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StorageMethod>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<StorageMethod>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StorageMethod>() {
            public StorageMethod findValueByNumber(int number) {
              return StorageMethod.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.janknspank.proto.Extensions.getDescriptor().getEnumTypes().get(1);
    }

    private static final StorageMethod[] VALUES = values();

    public static StorageMethod valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private StorageMethod(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:StorageMethod)
  }

  /**
   * Protobuf enum {@code ClientSerialization}
   */
  public enum ClientSerialization
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>INCLUDE = 1;</code>
     *
     * <pre>
     * Include this field in responses to the client, serialized with default
     * handling.
     * </pre>
     */
    INCLUDE(0, 1),
    /**
     * <code>INCLUDE_AS_NUMBER = 2;</code>
     *
     * <pre>
     * Include this field in responses to the client, serializing it as a
     * number even if precision / bits may be lost.
     * </pre>
     */
    INCLUDE_AS_NUMBER(1, 2),
    /**
     * <code>EXCLUDE = 3;</code>
     *
     * <pre>
     * Do not include this field in responses to the client.
     * </pre>
     */
    EXCLUDE(2, 3),
    ;

    /**
     * <code>INCLUDE = 1;</code>
     *
     * <pre>
     * Include this field in responses to the client, serialized with default
     * handling.
     * </pre>
     */
    public static final int INCLUDE_VALUE = 1;
    /**
     * <code>INCLUDE_AS_NUMBER = 2;</code>
     *
     * <pre>
     * Include this field in responses to the client, serializing it as a
     * number even if precision / bits may be lost.
     * </pre>
     */
    public static final int INCLUDE_AS_NUMBER_VALUE = 2;
    /**
     * <code>EXCLUDE = 3;</code>
     *
     * <pre>
     * Do not include this field in responses to the client.
     * </pre>
     */
    public static final int EXCLUDE_VALUE = 3;


    public final int getNumber() { return value; }

    public static ClientSerialization valueOf(int value) {
      switch (value) {
        case 1: return INCLUDE;
        case 2: return INCLUDE_AS_NUMBER;
        case 3: return EXCLUDE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ClientSerialization>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ClientSerialization>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ClientSerialization>() {
            public ClientSerialization findValueByNumber(int number) {
              return ClientSerialization.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.janknspank.proto.Extensions.getDescriptor().getEnumTypes().get(2);
    }

    private static final ClientSerialization[] VALUES = values();

    public static ClientSerialization valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ClientSerialization(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ClientSerialization)
  }

  public static final int REQUIRED_FIELD_NUMBER = 60001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      com.janknspank.proto.Extensions.Required> required = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.janknspank.proto.Extensions.Required.class,
        null);
  public static final int STORAGE_METHOD_FIELD_NUMBER = 60002;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      com.janknspank.proto.Extensions.StorageMethod> storageMethod = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.janknspank.proto.Extensions.StorageMethod.class,
        null);
  public static final int STRING_LENGTH_FIELD_NUMBER = 60003;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Integer> stringLength = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int CLIENT_SERIALIZATION_FIELD_NUMBER = 60004;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      com.janknspank.proto.Extensions.ClientSerialization> clientSerialization = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.janknspank.proto.Extensions.ClientSerialization.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%com/janknspank/proto/extensions.proto\032" +
      " google/protobuf/descriptor.proto*\033\n\010Req" +
      "uired\022\007\n\003YES\020\001\022\006\n\002NO\020\002*U\n\rStorageMethod\022" +
      "\010\n\004BLOB\020\001\022\017\n\013PRIMARY_KEY\020\002\022\t\n\005INDEX\020\003\022\020\n" +
      "\014UNIQUE_INDEX\020\004\022\014\n\010PULL_OUT\020\005*F\n\023ClientS" +
      "erialization\022\013\n\007INCLUDE\020\001\022\025\n\021INCLUDE_AS_" +
      "NUMBER\020\002\022\013\n\007EXCLUDE\020\003:@\n\010required\022\035.goog" +
      "le.protobuf.FieldOptions\030\341\324\003 \001(\0162\t.Requi" +
      "red:\002NO:M\n\016storage_method\022\035.google.proto" +
      "buf.FieldOptions\030\342\324\003 \001(\0162\016.StorageMethod",
      ":\004BLOB::\n\rstring_length\022\035.google.protobu" +
      "f.FieldOptions\030\343\324\003 \001(\005:\002-1:\\\n\024client_ser" +
      "ialization\022\035.google.protobuf.FieldOption" +
      "s\030\344\324\003 \001(\0162\024.ClientSerialization:\007INCLUDE" +
      "B\037\n\024com.janknspank.proto\200\001\000\210\001\000\220\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          required.internalInit(descriptor.getExtensions().get(0));
          storageMethod.internalInit(descriptor.getExtensions().get(1));
          stringLength.internalInit(descriptor.getExtensions().get(2));
          clientSerialization.internalInit(descriptor.getExtensions().get(3));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
