// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/janknspank/proto/interpreter.proto

package com.janknspank.proto;

public final class InterpreterProto {
  private InterpreterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&com/janknspank/proto/interpreter.proto" +
      "\032\"com/janknspank/proto/article.proto\032\037co" +
      "m/janknspank/proto/core.protoB(\n\024com.jan" +
      "knspank.protoB\020InterpreterProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.janknspank.proto.ArticleProto.getDescriptor(),
          com.janknspank.proto.CoreProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
