// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/janknspank/proto/interpreter.proto

package com.janknspank.proto;

public final class Interpreter {
  private Interpreter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InterpretedDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .Article article = 1;
    /**
     * <code>optional .Article article = 1;</code>
     */
    boolean hasArticle();
    /**
     * <code>optional .Article article = 1;</code>
     */
    com.janknspank.proto.Core.Article getArticle();
    /**
     * <code>optional .Article article = 1;</code>
     */
    com.janknspank.proto.Core.ArticleOrBuilder getArticleOrBuilder();

    // repeated string url = 3;
    /**
     * <code>repeated string url = 3;</code>
     */
    java.util.List<java.lang.String>
    getUrlList();
    /**
     * <code>repeated string url = 3;</code>
     */
    int getUrlCount();
    /**
     * <code>repeated string url = 3;</code>
     */
    java.lang.String getUrl(int index);
    /**
     * <code>repeated string url = 3;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes(int index);

    // repeated .ArticleKeyword keyword = 2;
    /**
     * <code>repeated .ArticleKeyword keyword = 2;</code>
     *
     * <pre>
     * TODO(jonemerson): This will become a list if Entities.
     * </pre>
     */
    java.util.List<com.janknspank.proto.Core.ArticleKeyword> 
        getKeywordList();
    /**
     * <code>repeated .ArticleKeyword keyword = 2;</code>
     *
     * <pre>
     * TODO(jonemerson): This will become a list if Entities.
     * </pre>
     */
    com.janknspank.proto.Core.ArticleKeyword getKeyword(int index);
    /**
     * <code>repeated .ArticleKeyword keyword = 2;</code>
     *
     * <pre>
     * TODO(jonemerson): This will become a list if Entities.
     * </pre>
     */
    int getKeywordCount();
    /**
     * <code>repeated .ArticleKeyword keyword = 2;</code>
     *
     * <pre>
     * TODO(jonemerson): This will become a list if Entities.
     * </pre>
     */
    java.util.List<? extends com.janknspank.proto.Core.ArticleKeywordOrBuilder> 
        getKeywordOrBuilderList();
    /**
     * <code>repeated .ArticleKeyword keyword = 2;</code>
     *
     * <pre>
     * TODO(jonemerson): This will become a list if Entities.
     * </pre>
     */
    com.janknspank.proto.Core.ArticleKeywordOrBuilder getKeywordOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code InterpretedData}
   */
  public static final class InterpretedData extends
      com.google.protobuf.GeneratedMessage
      implements InterpretedDataOrBuilder {
    // Use InterpretedData.newBuilder() to construct.
    private InterpretedData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InterpretedData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InterpretedData defaultInstance;
    public static InterpretedData getDefaultInstance() {
      return defaultInstance;
    }

    public InterpretedData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InterpretedData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.janknspank.proto.Core.Article.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = article_.toBuilder();
              }
              article_ = input.readMessage(com.janknspank.proto.Core.Article.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(article_);
                article_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                keyword_ = new java.util.ArrayList<com.janknspank.proto.Core.ArticleKeyword>();
                mutable_bitField0_ |= 0x00000004;
              }
              keyword_.add(input.readMessage(com.janknspank.proto.Core.ArticleKeyword.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                url_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              url_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          keyword_ = java.util.Collections.unmodifiableList(keyword_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          url_ = new com.google.protobuf.UnmodifiableLazyStringList(url_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.janknspank.proto.Interpreter.internal_static_InterpretedData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.janknspank.proto.Interpreter.internal_static_InterpretedData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.janknspank.proto.Interpreter.InterpretedData.class, com.janknspank.proto.Interpreter.InterpretedData.Builder.class);
    }

    public static com.google.protobuf.Parser<InterpretedData> PARSER =
        new com.google.protobuf.AbstractParser<InterpretedData>() {
      public InterpretedData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InterpretedData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InterpretedData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .Article article = 1;
    public static final int ARTICLE_FIELD_NUMBER = 1;
    private com.janknspank.proto.Core.Article article_;
    /**
     * <code>optional .Article article = 1;</code>
     */
    public boolean hasArticle() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Article article = 1;</code>
     */
    public com.janknspank.proto.Core.Article getArticle() {
      return article_;
    }
    /**
     * <code>optional .Article article = 1;</code>
     */
    public com.janknspank.proto.Core.ArticleOrBuilder getArticleOrBuilder() {
      return article_;
    }

    // repeated string url = 3;
    public static final int URL_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList url_;
    /**
     * <code>repeated string url = 3;</code>
     */
    public java.util.List<java.lang.String>
        getUrlList() {
      return url_;
    }
    /**
     * <code>repeated string url = 3;</code>
     */
    public int getUrlCount() {
      return url_.size();
    }
    /**
     * <code>repeated string url = 3;</code>
     */
    public java.lang.String getUrl(int index) {
      return url_.get(index);
    }
    /**
     * <code>repeated string url = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes(int index) {
      return url_.getByteString(index);
    }

    // repeated .ArticleKeyword keyword = 2;
    public static final int KEYWORD_FIELD_NUMBER = 2;
    private java.util.List<com.janknspank.proto.Core.ArticleKeyword> keyword_;
    /**
     * <code>repeated .ArticleKeyword keyword = 2;</code>
     *
     * <pre>
     * TODO(jonemerson): This will become a list if Entities.
     * </pre>
     */
    public java.util.List<com.janknspank.proto.Core.ArticleKeyword> getKeywordList() {
      return keyword_;
    }
    /**
     * <code>repeated .ArticleKeyword keyword = 2;</code>
     *
     * <pre>
     * TODO(jonemerson): This will become a list if Entities.
     * </pre>
     */
    public java.util.List<? extends com.janknspank.proto.Core.ArticleKeywordOrBuilder> 
        getKeywordOrBuilderList() {
      return keyword_;
    }
    /**
     * <code>repeated .ArticleKeyword keyword = 2;</code>
     *
     * <pre>
     * TODO(jonemerson): This will become a list if Entities.
     * </pre>
     */
    public int getKeywordCount() {
      return keyword_.size();
    }
    /**
     * <code>repeated .ArticleKeyword keyword = 2;</code>
     *
     * <pre>
     * TODO(jonemerson): This will become a list if Entities.
     * </pre>
     */
    public com.janknspank.proto.Core.ArticleKeyword getKeyword(int index) {
      return keyword_.get(index);
    }
    /**
     * <code>repeated .ArticleKeyword keyword = 2;</code>
     *
     * <pre>
     * TODO(jonemerson): This will become a list if Entities.
     * </pre>
     */
    public com.janknspank.proto.Core.ArticleKeywordOrBuilder getKeywordOrBuilder(
        int index) {
      return keyword_.get(index);
    }

    private void initFields() {
      article_ = com.janknspank.proto.Core.Article.getDefaultInstance();
      url_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      keyword_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasArticle()) {
        if (!getArticle().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, article_);
      }
      for (int i = 0; i < keyword_.size(); i++) {
        output.writeMessage(2, keyword_.get(i));
      }
      for (int i = 0; i < url_.size(); i++) {
        output.writeBytes(3, url_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, article_);
      }
      for (int i = 0; i < keyword_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, keyword_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < url_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(url_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getUrlList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.janknspank.proto.Interpreter.InterpretedData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.janknspank.proto.Interpreter.InterpretedData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.janknspank.proto.Interpreter.InterpretedData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.janknspank.proto.Interpreter.InterpretedData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.janknspank.proto.Interpreter.InterpretedData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.janknspank.proto.Interpreter.InterpretedData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.janknspank.proto.Interpreter.InterpretedData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.janknspank.proto.Interpreter.InterpretedData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.janknspank.proto.Interpreter.InterpretedData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.janknspank.proto.Interpreter.InterpretedData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.janknspank.proto.Interpreter.InterpretedData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InterpretedData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.janknspank.proto.Interpreter.InterpretedDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.janknspank.proto.Interpreter.internal_static_InterpretedData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.janknspank.proto.Interpreter.internal_static_InterpretedData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.janknspank.proto.Interpreter.InterpretedData.class, com.janknspank.proto.Interpreter.InterpretedData.Builder.class);
      }

      // Construct using com.janknspank.proto.Interpreter.InterpretedData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getArticleFieldBuilder();
          getKeywordFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (articleBuilder_ == null) {
          article_ = com.janknspank.proto.Core.Article.getDefaultInstance();
        } else {
          articleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        url_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (keywordBuilder_ == null) {
          keyword_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          keywordBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.janknspank.proto.Interpreter.internal_static_InterpretedData_descriptor;
      }

      public com.janknspank.proto.Interpreter.InterpretedData getDefaultInstanceForType() {
        return com.janknspank.proto.Interpreter.InterpretedData.getDefaultInstance();
      }

      public com.janknspank.proto.Interpreter.InterpretedData build() {
        com.janknspank.proto.Interpreter.InterpretedData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.janknspank.proto.Interpreter.InterpretedData buildPartial() {
        com.janknspank.proto.Interpreter.InterpretedData result = new com.janknspank.proto.Interpreter.InterpretedData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (articleBuilder_ == null) {
          result.article_ = article_;
        } else {
          result.article_ = articleBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          url_ = new com.google.protobuf.UnmodifiableLazyStringList(
              url_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.url_ = url_;
        if (keywordBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            keyword_ = java.util.Collections.unmodifiableList(keyword_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.keyword_ = keyword_;
        } else {
          result.keyword_ = keywordBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.janknspank.proto.Interpreter.InterpretedData) {
          return mergeFrom((com.janknspank.proto.Interpreter.InterpretedData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.janknspank.proto.Interpreter.InterpretedData other) {
        if (other == com.janknspank.proto.Interpreter.InterpretedData.getDefaultInstance()) return this;
        if (other.hasArticle()) {
          mergeArticle(other.getArticle());
        }
        if (!other.url_.isEmpty()) {
          if (url_.isEmpty()) {
            url_ = other.url_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureUrlIsMutable();
            url_.addAll(other.url_);
          }
          onChanged();
        }
        if (keywordBuilder_ == null) {
          if (!other.keyword_.isEmpty()) {
            if (keyword_.isEmpty()) {
              keyword_ = other.keyword_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureKeywordIsMutable();
              keyword_.addAll(other.keyword_);
            }
            onChanged();
          }
        } else {
          if (!other.keyword_.isEmpty()) {
            if (keywordBuilder_.isEmpty()) {
              keywordBuilder_.dispose();
              keywordBuilder_ = null;
              keyword_ = other.keyword_;
              bitField0_ = (bitField0_ & ~0x00000004);
              keywordBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getKeywordFieldBuilder() : null;
            } else {
              keywordBuilder_.addAllMessages(other.keyword_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasArticle()) {
          if (!getArticle().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.janknspank.proto.Interpreter.InterpretedData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.janknspank.proto.Interpreter.InterpretedData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .Article article = 1;
      private com.janknspank.proto.Core.Article article_ = com.janknspank.proto.Core.Article.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.janknspank.proto.Core.Article, com.janknspank.proto.Core.Article.Builder, com.janknspank.proto.Core.ArticleOrBuilder> articleBuilder_;
      /**
       * <code>optional .Article article = 1;</code>
       */
      public boolean hasArticle() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Article article = 1;</code>
       */
      public com.janknspank.proto.Core.Article getArticle() {
        if (articleBuilder_ == null) {
          return article_;
        } else {
          return articleBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Article article = 1;</code>
       */
      public Builder setArticle(com.janknspank.proto.Core.Article value) {
        if (articleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          article_ = value;
          onChanged();
        } else {
          articleBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Article article = 1;</code>
       */
      public Builder setArticle(
          com.janknspank.proto.Core.Article.Builder builderForValue) {
        if (articleBuilder_ == null) {
          article_ = builderForValue.build();
          onChanged();
        } else {
          articleBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Article article = 1;</code>
       */
      public Builder mergeArticle(com.janknspank.proto.Core.Article value) {
        if (articleBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              article_ != com.janknspank.proto.Core.Article.getDefaultInstance()) {
            article_ =
              com.janknspank.proto.Core.Article.newBuilder(article_).mergeFrom(value).buildPartial();
          } else {
            article_ = value;
          }
          onChanged();
        } else {
          articleBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Article article = 1;</code>
       */
      public Builder clearArticle() {
        if (articleBuilder_ == null) {
          article_ = com.janknspank.proto.Core.Article.getDefaultInstance();
          onChanged();
        } else {
          articleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .Article article = 1;</code>
       */
      public com.janknspank.proto.Core.Article.Builder getArticleBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getArticleFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Article article = 1;</code>
       */
      public com.janknspank.proto.Core.ArticleOrBuilder getArticleOrBuilder() {
        if (articleBuilder_ != null) {
          return articleBuilder_.getMessageOrBuilder();
        } else {
          return article_;
        }
      }
      /**
       * <code>optional .Article article = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.janknspank.proto.Core.Article, com.janknspank.proto.Core.Article.Builder, com.janknspank.proto.Core.ArticleOrBuilder> 
          getArticleFieldBuilder() {
        if (articleBuilder_ == null) {
          articleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.janknspank.proto.Core.Article, com.janknspank.proto.Core.Article.Builder, com.janknspank.proto.Core.ArticleOrBuilder>(
                  article_,
                  getParentForChildren(),
                  isClean());
          article_ = null;
        }
        return articleBuilder_;
      }

      // repeated string url = 3;
      private com.google.protobuf.LazyStringList url_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureUrlIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          url_ = new com.google.protobuf.LazyStringArrayList(url_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string url = 3;</code>
       */
      public java.util.List<java.lang.String>
          getUrlList() {
        return java.util.Collections.unmodifiableList(url_);
      }
      /**
       * <code>repeated string url = 3;</code>
       */
      public int getUrlCount() {
        return url_.size();
      }
      /**
       * <code>repeated string url = 3;</code>
       */
      public java.lang.String getUrl(int index) {
        return url_.get(index);
      }
      /**
       * <code>repeated string url = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes(int index) {
        return url_.getByteString(index);
      }
      /**
       * <code>repeated string url = 3;</code>
       */
      public Builder setUrl(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUrlIsMutable();
        url_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string url = 3;</code>
       */
      public Builder addUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUrlIsMutable();
        url_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string url = 3;</code>
       */
      public Builder addAllUrl(
          java.lang.Iterable<java.lang.String> values) {
        ensureUrlIsMutable();
        super.addAll(values, url_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string url = 3;</code>
       */
      public Builder clearUrl() {
        url_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string url = 3;</code>
       */
      public Builder addUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUrlIsMutable();
        url_.add(value);
        onChanged();
        return this;
      }

      // repeated .ArticleKeyword keyword = 2;
      private java.util.List<com.janknspank.proto.Core.ArticleKeyword> keyword_ =
        java.util.Collections.emptyList();
      private void ensureKeywordIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          keyword_ = new java.util.ArrayList<com.janknspank.proto.Core.ArticleKeyword>(keyword_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.janknspank.proto.Core.ArticleKeyword, com.janknspank.proto.Core.ArticleKeyword.Builder, com.janknspank.proto.Core.ArticleKeywordOrBuilder> keywordBuilder_;

      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public java.util.List<com.janknspank.proto.Core.ArticleKeyword> getKeywordList() {
        if (keywordBuilder_ == null) {
          return java.util.Collections.unmodifiableList(keyword_);
        } else {
          return keywordBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public int getKeywordCount() {
        if (keywordBuilder_ == null) {
          return keyword_.size();
        } else {
          return keywordBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public com.janknspank.proto.Core.ArticleKeyword getKeyword(int index) {
        if (keywordBuilder_ == null) {
          return keyword_.get(index);
        } else {
          return keywordBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public Builder setKeyword(
          int index, com.janknspank.proto.Core.ArticleKeyword value) {
        if (keywordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeywordIsMutable();
          keyword_.set(index, value);
          onChanged();
        } else {
          keywordBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public Builder setKeyword(
          int index, com.janknspank.proto.Core.ArticleKeyword.Builder builderForValue) {
        if (keywordBuilder_ == null) {
          ensureKeywordIsMutable();
          keyword_.set(index, builderForValue.build());
          onChanged();
        } else {
          keywordBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public Builder addKeyword(com.janknspank.proto.Core.ArticleKeyword value) {
        if (keywordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeywordIsMutable();
          keyword_.add(value);
          onChanged();
        } else {
          keywordBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public Builder addKeyword(
          int index, com.janknspank.proto.Core.ArticleKeyword value) {
        if (keywordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeywordIsMutable();
          keyword_.add(index, value);
          onChanged();
        } else {
          keywordBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public Builder addKeyword(
          com.janknspank.proto.Core.ArticleKeyword.Builder builderForValue) {
        if (keywordBuilder_ == null) {
          ensureKeywordIsMutable();
          keyword_.add(builderForValue.build());
          onChanged();
        } else {
          keywordBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public Builder addKeyword(
          int index, com.janknspank.proto.Core.ArticleKeyword.Builder builderForValue) {
        if (keywordBuilder_ == null) {
          ensureKeywordIsMutable();
          keyword_.add(index, builderForValue.build());
          onChanged();
        } else {
          keywordBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public Builder addAllKeyword(
          java.lang.Iterable<? extends com.janknspank.proto.Core.ArticleKeyword> values) {
        if (keywordBuilder_ == null) {
          ensureKeywordIsMutable();
          super.addAll(values, keyword_);
          onChanged();
        } else {
          keywordBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public Builder clearKeyword() {
        if (keywordBuilder_ == null) {
          keyword_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          keywordBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public Builder removeKeyword(int index) {
        if (keywordBuilder_ == null) {
          ensureKeywordIsMutable();
          keyword_.remove(index);
          onChanged();
        } else {
          keywordBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public com.janknspank.proto.Core.ArticleKeyword.Builder getKeywordBuilder(
          int index) {
        return getKeywordFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public com.janknspank.proto.Core.ArticleKeywordOrBuilder getKeywordOrBuilder(
          int index) {
        if (keywordBuilder_ == null) {
          return keyword_.get(index);  } else {
          return keywordBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public java.util.List<? extends com.janknspank.proto.Core.ArticleKeywordOrBuilder> 
           getKeywordOrBuilderList() {
        if (keywordBuilder_ != null) {
          return keywordBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(keyword_);
        }
      }
      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public com.janknspank.proto.Core.ArticleKeyword.Builder addKeywordBuilder() {
        return getKeywordFieldBuilder().addBuilder(
            com.janknspank.proto.Core.ArticleKeyword.getDefaultInstance());
      }
      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public com.janknspank.proto.Core.ArticleKeyword.Builder addKeywordBuilder(
          int index) {
        return getKeywordFieldBuilder().addBuilder(
            index, com.janknspank.proto.Core.ArticleKeyword.getDefaultInstance());
      }
      /**
       * <code>repeated .ArticleKeyword keyword = 2;</code>
       *
       * <pre>
       * TODO(jonemerson): This will become a list if Entities.
       * </pre>
       */
      public java.util.List<com.janknspank.proto.Core.ArticleKeyword.Builder> 
           getKeywordBuilderList() {
        return getKeywordFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.janknspank.proto.Core.ArticleKeyword, com.janknspank.proto.Core.ArticleKeyword.Builder, com.janknspank.proto.Core.ArticleKeywordOrBuilder> 
          getKeywordFieldBuilder() {
        if (keywordBuilder_ == null) {
          keywordBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.janknspank.proto.Core.ArticleKeyword, com.janknspank.proto.Core.ArticleKeyword.Builder, com.janknspank.proto.Core.ArticleKeywordOrBuilder>(
                  keyword_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          keyword_ = null;
        }
        return keywordBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:InterpretedData)
    }

    static {
      defaultInstance = new InterpretedData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:InterpretedData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_InterpretedData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_InterpretedData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&com/janknspank/proto/interpreter.proto" +
      "\032\037com/janknspank/proto/core.proto\"[\n\017Int" +
      "erpretedData\022\031\n\007article\030\001 \001(\0132\010.Article\022" +
      "\013\n\003url\030\003 \003(\t\022 \n\007keyword\030\002 \003(\0132\017.ArticleK" +
      "eywordB\026\n\024com.janknspank.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_InterpretedData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_InterpretedData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_InterpretedData_descriptor,
              new java.lang.String[] { "Article", "Url", "Keyword", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.janknspank.proto.Core.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
