// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/janknspank/proto/local.proto

package com.janknspank.proto;

public final class LocalProto {
  private LocalProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TokenToEntityOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string token = 1;
    /**
     * <code>optional string token = 1;</code>
     */
    boolean hasToken();
    /**
     * <code>optional string token = 1;</code>
     */
    java.lang.String getToken();
    /**
     * <code>optional string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    // optional string entity_keyword = 2;
    /**
     * <code>optional string entity_keyword = 2;</code>
     */
    boolean hasEntityKeyword();
    /**
     * <code>optional string entity_keyword = 2;</code>
     */
    java.lang.String getEntityKeyword();
    /**
     * <code>optional string entity_keyword = 2;</code>
     */
    com.google.protobuf.ByteString
        getEntityKeywordBytes();

    // optional string entity_type = 3;
    /**
     * <code>optional string entity_type = 3;</code>
     */
    boolean hasEntityType();
    /**
     * <code>optional string entity_type = 3;</code>
     */
    java.lang.String getEntityType();
    /**
     * <code>optional string entity_type = 3;</code>
     */
    com.google.protobuf.ByteString
        getEntityTypeBytes();
  }
  /**
   * Protobuf type {@code TokenToEntity}
   */
  public static final class TokenToEntity extends
      com.google.protobuf.GeneratedMessage
      implements TokenToEntityOrBuilder {
    // Use TokenToEntity.newBuilder() to construct.
    private TokenToEntity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TokenToEntity(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TokenToEntity defaultInstance;
    public static TokenToEntity getDefaultInstance() {
      return defaultInstance;
    }

    public TokenToEntity getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TokenToEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              token_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              entityKeyword_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              entityType_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.janknspank.proto.LocalProto.internal_static_TokenToEntity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.janknspank.proto.LocalProto.internal_static_TokenToEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.janknspank.proto.LocalProto.TokenToEntity.class, com.janknspank.proto.LocalProto.TokenToEntity.Builder.class);
    }

    public static com.google.protobuf.Parser<TokenToEntity> PARSER =
        new com.google.protobuf.AbstractParser<TokenToEntity>() {
      public TokenToEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TokenToEntity(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TokenToEntity> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string token = 1;
    public static final int TOKEN_FIELD_NUMBER = 1;
    private java.lang.Object token_;
    /**
     * <code>optional string token = 1;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string token = 1;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string entity_keyword = 2;
    public static final int ENTITY_KEYWORD_FIELD_NUMBER = 2;
    private java.lang.Object entityKeyword_;
    /**
     * <code>optional string entity_keyword = 2;</code>
     */
    public boolean hasEntityKeyword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string entity_keyword = 2;</code>
     */
    public java.lang.String getEntityKeyword() {
      java.lang.Object ref = entityKeyword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          entityKeyword_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string entity_keyword = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEntityKeywordBytes() {
      java.lang.Object ref = entityKeyword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entityKeyword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string entity_type = 3;
    public static final int ENTITY_TYPE_FIELD_NUMBER = 3;
    private java.lang.Object entityType_;
    /**
     * <code>optional string entity_type = 3;</code>
     */
    public boolean hasEntityType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string entity_type = 3;</code>
     */
    public java.lang.String getEntityType() {
      java.lang.Object ref = entityType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          entityType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string entity_type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEntityTypeBytes() {
      java.lang.Object ref = entityType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entityType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      token_ = "";
      entityKeyword_ = "";
      entityType_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEntityKeywordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEntityTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEntityKeywordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEntityTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.janknspank.proto.LocalProto.TokenToEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.janknspank.proto.LocalProto.TokenToEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.janknspank.proto.LocalProto.TokenToEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.janknspank.proto.LocalProto.TokenToEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.janknspank.proto.LocalProto.TokenToEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.janknspank.proto.LocalProto.TokenToEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.janknspank.proto.LocalProto.TokenToEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.janknspank.proto.LocalProto.TokenToEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.janknspank.proto.LocalProto.TokenToEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.janknspank.proto.LocalProto.TokenToEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.janknspank.proto.LocalProto.TokenToEntity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TokenToEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.janknspank.proto.LocalProto.TokenToEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.janknspank.proto.LocalProto.internal_static_TokenToEntity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.janknspank.proto.LocalProto.internal_static_TokenToEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.janknspank.proto.LocalProto.TokenToEntity.class, com.janknspank.proto.LocalProto.TokenToEntity.Builder.class);
      }

      // Construct using com.janknspank.proto.LocalProto.TokenToEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        entityKeyword_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        entityType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.janknspank.proto.LocalProto.internal_static_TokenToEntity_descriptor;
      }

      public com.janknspank.proto.LocalProto.TokenToEntity getDefaultInstanceForType() {
        return com.janknspank.proto.LocalProto.TokenToEntity.getDefaultInstance();
      }

      public com.janknspank.proto.LocalProto.TokenToEntity build() {
        com.janknspank.proto.LocalProto.TokenToEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.janknspank.proto.LocalProto.TokenToEntity buildPartial() {
        com.janknspank.proto.LocalProto.TokenToEntity result = new com.janknspank.proto.LocalProto.TokenToEntity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.entityKeyword_ = entityKeyword_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.entityType_ = entityType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.janknspank.proto.LocalProto.TokenToEntity) {
          return mergeFrom((com.janknspank.proto.LocalProto.TokenToEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.janknspank.proto.LocalProto.TokenToEntity other) {
        if (other == com.janknspank.proto.LocalProto.TokenToEntity.getDefaultInstance()) return this;
        if (other.hasToken()) {
          bitField0_ |= 0x00000001;
          token_ = other.token_;
          onChanged();
        }
        if (other.hasEntityKeyword()) {
          bitField0_ |= 0x00000002;
          entityKeyword_ = other.entityKeyword_;
          onChanged();
        }
        if (other.hasEntityType()) {
          bitField0_ |= 0x00000004;
          entityType_ = other.entityType_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.janknspank.proto.LocalProto.TokenToEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.janknspank.proto.LocalProto.TokenToEntity) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string token = 1;
      private java.lang.Object token_ = "";
      /**
       * <code>optional string token = 1;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string token = 1;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 1;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 1;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 1;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }

      // optional string entity_keyword = 2;
      private java.lang.Object entityKeyword_ = "";
      /**
       * <code>optional string entity_keyword = 2;</code>
       */
      public boolean hasEntityKeyword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string entity_keyword = 2;</code>
       */
      public java.lang.String getEntityKeyword() {
        java.lang.Object ref = entityKeyword_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          entityKeyword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string entity_keyword = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEntityKeywordBytes() {
        java.lang.Object ref = entityKeyword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          entityKeyword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string entity_keyword = 2;</code>
       */
      public Builder setEntityKeyword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        entityKeyword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string entity_keyword = 2;</code>
       */
      public Builder clearEntityKeyword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        entityKeyword_ = getDefaultInstance().getEntityKeyword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string entity_keyword = 2;</code>
       */
      public Builder setEntityKeywordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        entityKeyword_ = value;
        onChanged();
        return this;
      }

      // optional string entity_type = 3;
      private java.lang.Object entityType_ = "";
      /**
       * <code>optional string entity_type = 3;</code>
       */
      public boolean hasEntityType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string entity_type = 3;</code>
       */
      public java.lang.String getEntityType() {
        java.lang.Object ref = entityType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          entityType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string entity_type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEntityTypeBytes() {
        java.lang.Object ref = entityType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          entityType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string entity_type = 3;</code>
       */
      public Builder setEntityType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        entityType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string entity_type = 3;</code>
       */
      public Builder clearEntityType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        entityType_ = getDefaultInstance().getEntityType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string entity_type = 3;</code>
       */
      public Builder setEntityTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        entityType_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TokenToEntity)
    }

    static {
      defaultInstance = new TokenToEntity(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TokenToEntity)
  }

  public interface LongAbstractOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string article_name = 1;
    /**
     * <code>optional string article_name = 1;</code>
     */
    boolean hasArticleName();
    /**
     * <code>optional string article_name = 1;</code>
     */
    java.lang.String getArticleName();
    /**
     * <code>optional string article_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getArticleNameBytes();

    // optional string topic = 2;
    /**
     * <code>optional string topic = 2;</code>
     */
    boolean hasTopic();
    /**
     * <code>optional string topic = 2;</code>
     */
    java.lang.String getTopic();
    /**
     * <code>optional string topic = 2;</code>
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    // optional string text = 3;
    /**
     * <code>optional string text = 3;</code>
     */
    boolean hasText();
    /**
     * <code>optional string text = 3;</code>
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 3;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code LongAbstract}
   */
  public static final class LongAbstract extends
      com.google.protobuf.GeneratedMessage
      implements LongAbstractOrBuilder {
    // Use LongAbstract.newBuilder() to construct.
    private LongAbstract(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LongAbstract(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LongAbstract defaultInstance;
    public static LongAbstract getDefaultInstance() {
      return defaultInstance;
    }

    public LongAbstract getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LongAbstract(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              articleName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              topic_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              text_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.janknspank.proto.LocalProto.internal_static_LongAbstract_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.janknspank.proto.LocalProto.internal_static_LongAbstract_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.janknspank.proto.LocalProto.LongAbstract.class, com.janknspank.proto.LocalProto.LongAbstract.Builder.class);
    }

    public static com.google.protobuf.Parser<LongAbstract> PARSER =
        new com.google.protobuf.AbstractParser<LongAbstract>() {
      public LongAbstract parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LongAbstract(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LongAbstract> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string article_name = 1;
    public static final int ARTICLE_NAME_FIELD_NUMBER = 1;
    private java.lang.Object articleName_;
    /**
     * <code>optional string article_name = 1;</code>
     */
    public boolean hasArticleName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string article_name = 1;</code>
     */
    public java.lang.String getArticleName() {
      java.lang.Object ref = articleName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          articleName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string article_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getArticleNameBytes() {
      java.lang.Object ref = articleName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        articleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string topic = 2;
    public static final int TOPIC_FIELD_NUMBER = 2;
    private java.lang.Object topic_;
    /**
     * <code>optional string topic = 2;</code>
     */
    public boolean hasTopic() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string topic = 2;</code>
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          topic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string topic = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string text = 3;
    public static final int TEXT_FIELD_NUMBER = 3;
    private java.lang.Object text_;
    /**
     * <code>optional string text = 3;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string text = 3;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string text = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      articleName_ = "";
      topic_ = "";
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getArticleNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTopicBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getArticleNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTopicBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.janknspank.proto.LocalProto.LongAbstract parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.janknspank.proto.LocalProto.LongAbstract parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.janknspank.proto.LocalProto.LongAbstract parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.janknspank.proto.LocalProto.LongAbstract parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.janknspank.proto.LocalProto.LongAbstract parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.janknspank.proto.LocalProto.LongAbstract parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.janknspank.proto.LocalProto.LongAbstract parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.janknspank.proto.LocalProto.LongAbstract parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.janknspank.proto.LocalProto.LongAbstract parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.janknspank.proto.LocalProto.LongAbstract parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.janknspank.proto.LocalProto.LongAbstract prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LongAbstract}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.janknspank.proto.LocalProto.LongAbstractOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.janknspank.proto.LocalProto.internal_static_LongAbstract_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.janknspank.proto.LocalProto.internal_static_LongAbstract_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.janknspank.proto.LocalProto.LongAbstract.class, com.janknspank.proto.LocalProto.LongAbstract.Builder.class);
      }

      // Construct using com.janknspank.proto.LocalProto.LongAbstract.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        articleName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        topic_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.janknspank.proto.LocalProto.internal_static_LongAbstract_descriptor;
      }

      public com.janknspank.proto.LocalProto.LongAbstract getDefaultInstanceForType() {
        return com.janknspank.proto.LocalProto.LongAbstract.getDefaultInstance();
      }

      public com.janknspank.proto.LocalProto.LongAbstract build() {
        com.janknspank.proto.LocalProto.LongAbstract result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.janknspank.proto.LocalProto.LongAbstract buildPartial() {
        com.janknspank.proto.LocalProto.LongAbstract result = new com.janknspank.proto.LocalProto.LongAbstract(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.articleName_ = articleName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.topic_ = topic_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.janknspank.proto.LocalProto.LongAbstract) {
          return mergeFrom((com.janknspank.proto.LocalProto.LongAbstract)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.janknspank.proto.LocalProto.LongAbstract other) {
        if (other == com.janknspank.proto.LocalProto.LongAbstract.getDefaultInstance()) return this;
        if (other.hasArticleName()) {
          bitField0_ |= 0x00000001;
          articleName_ = other.articleName_;
          onChanged();
        }
        if (other.hasTopic()) {
          bitField0_ |= 0x00000002;
          topic_ = other.topic_;
          onChanged();
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000004;
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.janknspank.proto.LocalProto.LongAbstract parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.janknspank.proto.LocalProto.LongAbstract) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string article_name = 1;
      private java.lang.Object articleName_ = "";
      /**
       * <code>optional string article_name = 1;</code>
       */
      public boolean hasArticleName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string article_name = 1;</code>
       */
      public java.lang.String getArticleName() {
        java.lang.Object ref = articleName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          articleName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string article_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getArticleNameBytes() {
        java.lang.Object ref = articleName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          articleName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string article_name = 1;</code>
       */
      public Builder setArticleName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        articleName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string article_name = 1;</code>
       */
      public Builder clearArticleName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        articleName_ = getDefaultInstance().getArticleName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string article_name = 1;</code>
       */
      public Builder setArticleNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        articleName_ = value;
        onChanged();
        return this;
      }

      // optional string topic = 2;
      private java.lang.Object topic_ = "";
      /**
       * <code>optional string topic = 2;</code>
       */
      public boolean hasTopic() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string topic = 2;</code>
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string topic = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string topic = 2;</code>
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string topic = 2;</code>
       */
      public Builder clearTopic() {
        bitField0_ = (bitField0_ & ~0x00000002);
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>optional string topic = 2;</code>
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        topic_ = value;
        onChanged();
        return this;
      }

      // optional string text = 3;
      private java.lang.Object text_ = "";
      /**
       * <code>optional string text = 3;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string text = 3;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text = 3;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 3;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 3;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LongAbstract)
    }

    static {
      defaultInstance = new LongAbstract(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LongAbstract)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TokenToEntity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TokenToEntity_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LongAbstract_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LongAbstract_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n com/janknspank/proto/local.proto\032(com/" +
      "janknspank/database/extensions.proto\032\037co" +
      "m/janknspank/proto/core.proto\"m\n\rTokenTo" +
      "Entity\022\033\n\005token\030\001 \001(\tB\014\210\246\035\001\220\246\035\003\230\246\035d\022 \n\016e" +
      "ntity_keyword\030\002 \001(\tB\010\210\246\035\001\230\246\035d\022\035\n\013entity_" +
      "type\030\003 \001(\tB\010\210\246\035\001\230\246\035\005\"e\n\014LongAbstract\022\"\n\014" +
      "article_name\030\001 \001(\tB\014\210\246\035\001\220\246\035\002\230\246\035x\022\027\n\005topi" +
      "c\030\002 \001(\tB\010\210\246\035\001\230\246\035d\022\030\n\004text\030\003 \001(\tB\n\210\246\035\001\230\246\035" +
      "\377\377\003B\"\n\024com.janknspank.protoB\nLocalProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TokenToEntity_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TokenToEntity_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TokenToEntity_descriptor,
              new java.lang.String[] { "Token", "EntityKeyword", "EntityType", });
          internal_static_LongAbstract_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_LongAbstract_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LongAbstract_descriptor,
              new java.lang.String[] { "ArticleName", "Topic", "Text", });
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registry.add(com.janknspank.database.ExtensionsProto.required);
          registry.add(com.janknspank.database.ExtensionsProto.storageMethod);
          registry.add(com.janknspank.database.ExtensionsProto.stringLength);
          registry.add(com.janknspank.database.ExtensionsProto.required);
          registry.add(com.janknspank.database.ExtensionsProto.stringLength);
          registry.add(com.janknspank.database.ExtensionsProto.required);
          registry.add(com.janknspank.database.ExtensionsProto.stringLength);
          registry.add(com.janknspank.database.ExtensionsProto.required);
          registry.add(com.janknspank.database.ExtensionsProto.storageMethod);
          registry.add(com.janknspank.database.ExtensionsProto.stringLength);
          registry.add(com.janknspank.database.ExtensionsProto.required);
          registry.add(com.janknspank.database.ExtensionsProto.stringLength);
          registry.add(com.janknspank.database.ExtensionsProto.required);
          registry.add(com.janknspank.database.ExtensionsProto.stringLength);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.janknspank.database.ExtensionsProto.getDescriptor(),
          com.janknspank.proto.CoreProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
