// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/janknspank/proto/rank.proto

package com.janknspank.proto;

public final class RankProto {
  private RankProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonaOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string name = 1;
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * A name for this person.  Not really used for much of anything now,
     * but helpful to keep in mind who our different personas are so we can
     * talk about them.
     * </pre>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * A name for this person.  Not really used for much of anything now,
     * but helpful to keep in mind who our different personas are so we can
     * talk about them.
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * A name for this person.  Not really used for much of anything now,
     * but helpful to keep in mind who our different personas are so we can
     * talk about them.
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string email = 2;
    /**
     * <code>optional string email = 2;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 2;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 2;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // repeated string good_url = 3;
    /**
     * <code>repeated string good_url = 3;</code>
     */
    java.util.List<java.lang.String>
    getGoodUrlList();
    /**
     * <code>repeated string good_url = 3;</code>
     */
    int getGoodUrlCount();
    /**
     * <code>repeated string good_url = 3;</code>
     */
    java.lang.String getGoodUrl(int index);
    /**
     * <code>repeated string good_url = 3;</code>
     */
    com.google.protobuf.ByteString
        getGoodUrlBytes(int index);

    // repeated string bad_url = 4;
    /**
     * <code>repeated string bad_url = 4;</code>
     */
    java.util.List<java.lang.String>
    getBadUrlList();
    /**
     * <code>repeated string bad_url = 4;</code>
     */
    int getBadUrlCount();
    /**
     * <code>repeated string bad_url = 4;</code>
     */
    java.lang.String getBadUrl(int index);
    /**
     * <code>repeated string bad_url = 4;</code>
     */
    com.google.protobuf.ByteString
        getBadUrlBytes(int index);

    // repeated string linked_in_contact_name = 5;
    /**
     * <code>repeated string linked_in_contact_name = 5;</code>
     */
    java.util.List<java.lang.String>
    getLinkedInContactNameList();
    /**
     * <code>repeated string linked_in_contact_name = 5;</code>
     */
    int getLinkedInContactNameCount();
    /**
     * <code>repeated string linked_in_contact_name = 5;</code>
     */
    java.lang.String getLinkedInContactName(int index);
    /**
     * <code>repeated string linked_in_contact_name = 5;</code>
     */
    com.google.protobuf.ByteString
        getLinkedInContactNameBytes(int index);

    // repeated string address_book_contact_name = 6;
    /**
     * <code>repeated string address_book_contact_name = 6;</code>
     */
    java.util.List<java.lang.String>
    getAddressBookContactNameList();
    /**
     * <code>repeated string address_book_contact_name = 6;</code>
     */
    int getAddressBookContactNameCount();
    /**
     * <code>repeated string address_book_contact_name = 6;</code>
     */
    java.lang.String getAddressBookContactName(int index);
    /**
     * <code>repeated string address_book_contact_name = 6;</code>
     */
    com.google.protobuf.ByteString
        getAddressBookContactNameBytes(int index);

    // repeated .Interest interest = 7;
    /**
     * <code>repeated .Interest interest = 7;</code>
     */
    java.util.List<com.janknspank.proto.UserProto.Interest> 
        getInterestList();
    /**
     * <code>repeated .Interest interest = 7;</code>
     */
    com.janknspank.proto.UserProto.Interest getInterest(int index);
    /**
     * <code>repeated .Interest interest = 7;</code>
     */
    int getInterestCount();
    /**
     * <code>repeated .Interest interest = 7;</code>
     */
    java.util.List<? extends com.janknspank.proto.UserProto.InterestOrBuilder> 
        getInterestOrBuilderList();
    /**
     * <code>repeated .Interest interest = 7;</code>
     */
    com.janknspank.proto.UserProto.InterestOrBuilder getInterestOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Persona}
   */
  public static final class Persona extends
      com.google.protobuf.GeneratedMessage
      implements PersonaOrBuilder {
    // Use Persona.newBuilder() to construct.
    private Persona(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Persona(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Persona defaultInstance;
    public static Persona getDefaultInstance() {
      return defaultInstance;
    }

    public Persona getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Persona(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              email_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                goodUrl_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              goodUrl_.add(input.readBytes());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                badUrl_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              badUrl_.add(input.readBytes());
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                linkedInContactName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              linkedInContactName_.add(input.readBytes());
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                addressBookContactName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              addressBookContactName_.add(input.readBytes());
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                interest_ = new java.util.ArrayList<com.janknspank.proto.UserProto.Interest>();
                mutable_bitField0_ |= 0x00000040;
              }
              interest_.add(input.readMessage(com.janknspank.proto.UserProto.Interest.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          goodUrl_ = new com.google.protobuf.UnmodifiableLazyStringList(goodUrl_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          badUrl_ = new com.google.protobuf.UnmodifiableLazyStringList(badUrl_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          linkedInContactName_ = new com.google.protobuf.UnmodifiableLazyStringList(linkedInContactName_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          addressBookContactName_ = new com.google.protobuf.UnmodifiableLazyStringList(addressBookContactName_);
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          interest_ = java.util.Collections.unmodifiableList(interest_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.janknspank.proto.RankProto.internal_static_Persona_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.janknspank.proto.RankProto.internal_static_Persona_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.janknspank.proto.RankProto.Persona.class, com.janknspank.proto.RankProto.Persona.Builder.class);
    }

    public static com.google.protobuf.Parser<Persona> PARSER =
        new com.google.protobuf.AbstractParser<Persona>() {
      public Persona parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Persona(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Persona> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * A name for this person.  Not really used for much of anything now,
     * but helpful to keep in mind who our different personas are so we can
     * talk about them.
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * A name for this person.  Not really used for much of anything now,
     * but helpful to keep in mind who our different personas are so we can
     * talk about them.
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * A name for this person.  Not really used for much of anything now,
     * but helpful to keep in mind who our different personas are so we can
     * talk about them.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string email = 2;
    public static final int EMAIL_FIELD_NUMBER = 2;
    private java.lang.Object email_;
    /**
     * <code>optional string email = 2;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string email = 2;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string good_url = 3;
    public static final int GOOD_URL_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList goodUrl_;
    /**
     * <code>repeated string good_url = 3;</code>
     */
    public java.util.List<java.lang.String>
        getGoodUrlList() {
      return goodUrl_;
    }
    /**
     * <code>repeated string good_url = 3;</code>
     */
    public int getGoodUrlCount() {
      return goodUrl_.size();
    }
    /**
     * <code>repeated string good_url = 3;</code>
     */
    public java.lang.String getGoodUrl(int index) {
      return goodUrl_.get(index);
    }
    /**
     * <code>repeated string good_url = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGoodUrlBytes(int index) {
      return goodUrl_.getByteString(index);
    }

    // repeated string bad_url = 4;
    public static final int BAD_URL_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList badUrl_;
    /**
     * <code>repeated string bad_url = 4;</code>
     */
    public java.util.List<java.lang.String>
        getBadUrlList() {
      return badUrl_;
    }
    /**
     * <code>repeated string bad_url = 4;</code>
     */
    public int getBadUrlCount() {
      return badUrl_.size();
    }
    /**
     * <code>repeated string bad_url = 4;</code>
     */
    public java.lang.String getBadUrl(int index) {
      return badUrl_.get(index);
    }
    /**
     * <code>repeated string bad_url = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBadUrlBytes(int index) {
      return badUrl_.getByteString(index);
    }

    // repeated string linked_in_contact_name = 5;
    public static final int LINKED_IN_CONTACT_NAME_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList linkedInContactName_;
    /**
     * <code>repeated string linked_in_contact_name = 5;</code>
     */
    public java.util.List<java.lang.String>
        getLinkedInContactNameList() {
      return linkedInContactName_;
    }
    /**
     * <code>repeated string linked_in_contact_name = 5;</code>
     */
    public int getLinkedInContactNameCount() {
      return linkedInContactName_.size();
    }
    /**
     * <code>repeated string linked_in_contact_name = 5;</code>
     */
    public java.lang.String getLinkedInContactName(int index) {
      return linkedInContactName_.get(index);
    }
    /**
     * <code>repeated string linked_in_contact_name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLinkedInContactNameBytes(int index) {
      return linkedInContactName_.getByteString(index);
    }

    // repeated string address_book_contact_name = 6;
    public static final int ADDRESS_BOOK_CONTACT_NAME_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList addressBookContactName_;
    /**
     * <code>repeated string address_book_contact_name = 6;</code>
     */
    public java.util.List<java.lang.String>
        getAddressBookContactNameList() {
      return addressBookContactName_;
    }
    /**
     * <code>repeated string address_book_contact_name = 6;</code>
     */
    public int getAddressBookContactNameCount() {
      return addressBookContactName_.size();
    }
    /**
     * <code>repeated string address_book_contact_name = 6;</code>
     */
    public java.lang.String getAddressBookContactName(int index) {
      return addressBookContactName_.get(index);
    }
    /**
     * <code>repeated string address_book_contact_name = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBookContactNameBytes(int index) {
      return addressBookContactName_.getByteString(index);
    }

    // repeated .Interest interest = 7;
    public static final int INTEREST_FIELD_NUMBER = 7;
    private java.util.List<com.janknspank.proto.UserProto.Interest> interest_;
    /**
     * <code>repeated .Interest interest = 7;</code>
     */
    public java.util.List<com.janknspank.proto.UserProto.Interest> getInterestList() {
      return interest_;
    }
    /**
     * <code>repeated .Interest interest = 7;</code>
     */
    public java.util.List<? extends com.janknspank.proto.UserProto.InterestOrBuilder> 
        getInterestOrBuilderList() {
      return interest_;
    }
    /**
     * <code>repeated .Interest interest = 7;</code>
     */
    public int getInterestCount() {
      return interest_.size();
    }
    /**
     * <code>repeated .Interest interest = 7;</code>
     */
    public com.janknspank.proto.UserProto.Interest getInterest(int index) {
      return interest_.get(index);
    }
    /**
     * <code>repeated .Interest interest = 7;</code>
     */
    public com.janknspank.proto.UserProto.InterestOrBuilder getInterestOrBuilder(
        int index) {
      return interest_.get(index);
    }

    private void initFields() {
      name_ = "";
      email_ = "";
      goodUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      badUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      linkedInContactName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      addressBookContactName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      interest_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEmailBytes());
      }
      for (int i = 0; i < goodUrl_.size(); i++) {
        output.writeBytes(3, goodUrl_.getByteString(i));
      }
      for (int i = 0; i < badUrl_.size(); i++) {
        output.writeBytes(4, badUrl_.getByteString(i));
      }
      for (int i = 0; i < linkedInContactName_.size(); i++) {
        output.writeBytes(5, linkedInContactName_.getByteString(i));
      }
      for (int i = 0; i < addressBookContactName_.size(); i++) {
        output.writeBytes(6, addressBookContactName_.getByteString(i));
      }
      for (int i = 0; i < interest_.size(); i++) {
        output.writeMessage(7, interest_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEmailBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < goodUrl_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(goodUrl_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getGoodUrlList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < badUrl_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(badUrl_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getBadUrlList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < linkedInContactName_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(linkedInContactName_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getLinkedInContactNameList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < addressBookContactName_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(addressBookContactName_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getAddressBookContactNameList().size();
      }
      for (int i = 0; i < interest_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, interest_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.janknspank.proto.RankProto.Persona parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.janknspank.proto.RankProto.Persona parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.janknspank.proto.RankProto.Persona parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.janknspank.proto.RankProto.Persona parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.janknspank.proto.RankProto.Persona parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.janknspank.proto.RankProto.Persona parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.janknspank.proto.RankProto.Persona parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.janknspank.proto.RankProto.Persona parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.janknspank.proto.RankProto.Persona parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.janknspank.proto.RankProto.Persona parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.janknspank.proto.RankProto.Persona prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Persona}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.janknspank.proto.RankProto.PersonaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.janknspank.proto.RankProto.internal_static_Persona_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.janknspank.proto.RankProto.internal_static_Persona_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.janknspank.proto.RankProto.Persona.class, com.janknspank.proto.RankProto.Persona.Builder.class);
      }

      // Construct using com.janknspank.proto.RankProto.Persona.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInterestFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        goodUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        badUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        linkedInContactName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        addressBookContactName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (interestBuilder_ == null) {
          interest_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          interestBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.janknspank.proto.RankProto.internal_static_Persona_descriptor;
      }

      public com.janknspank.proto.RankProto.Persona getDefaultInstanceForType() {
        return com.janknspank.proto.RankProto.Persona.getDefaultInstance();
      }

      public com.janknspank.proto.RankProto.Persona build() {
        com.janknspank.proto.RankProto.Persona result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.janknspank.proto.RankProto.Persona buildPartial() {
        com.janknspank.proto.RankProto.Persona result = new com.janknspank.proto.RankProto.Persona(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.email_ = email_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          goodUrl_ = new com.google.protobuf.UnmodifiableLazyStringList(
              goodUrl_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.goodUrl_ = goodUrl_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          badUrl_ = new com.google.protobuf.UnmodifiableLazyStringList(
              badUrl_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.badUrl_ = badUrl_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          linkedInContactName_ = new com.google.protobuf.UnmodifiableLazyStringList(
              linkedInContactName_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.linkedInContactName_ = linkedInContactName_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          addressBookContactName_ = new com.google.protobuf.UnmodifiableLazyStringList(
              addressBookContactName_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.addressBookContactName_ = addressBookContactName_;
        if (interestBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            interest_ = java.util.Collections.unmodifiableList(interest_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.interest_ = interest_;
        } else {
          result.interest_ = interestBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.janknspank.proto.RankProto.Persona) {
          return mergeFrom((com.janknspank.proto.RankProto.Persona)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.janknspank.proto.RankProto.Persona other) {
        if (other == com.janknspank.proto.RankProto.Persona.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000002;
          email_ = other.email_;
          onChanged();
        }
        if (!other.goodUrl_.isEmpty()) {
          if (goodUrl_.isEmpty()) {
            goodUrl_ = other.goodUrl_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureGoodUrlIsMutable();
            goodUrl_.addAll(other.goodUrl_);
          }
          onChanged();
        }
        if (!other.badUrl_.isEmpty()) {
          if (badUrl_.isEmpty()) {
            badUrl_ = other.badUrl_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureBadUrlIsMutable();
            badUrl_.addAll(other.badUrl_);
          }
          onChanged();
        }
        if (!other.linkedInContactName_.isEmpty()) {
          if (linkedInContactName_.isEmpty()) {
            linkedInContactName_ = other.linkedInContactName_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureLinkedInContactNameIsMutable();
            linkedInContactName_.addAll(other.linkedInContactName_);
          }
          onChanged();
        }
        if (!other.addressBookContactName_.isEmpty()) {
          if (addressBookContactName_.isEmpty()) {
            addressBookContactName_ = other.addressBookContactName_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureAddressBookContactNameIsMutable();
            addressBookContactName_.addAll(other.addressBookContactName_);
          }
          onChanged();
        }
        if (interestBuilder_ == null) {
          if (!other.interest_.isEmpty()) {
            if (interest_.isEmpty()) {
              interest_ = other.interest_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureInterestIsMutable();
              interest_.addAll(other.interest_);
            }
            onChanged();
          }
        } else {
          if (!other.interest_.isEmpty()) {
            if (interestBuilder_.isEmpty()) {
              interestBuilder_.dispose();
              interestBuilder_ = null;
              interest_ = other.interest_;
              bitField0_ = (bitField0_ & ~0x00000040);
              interestBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInterestFieldBuilder() : null;
            } else {
              interestBuilder_.addAllMessages(other.interest_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.janknspank.proto.RankProto.Persona parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.janknspank.proto.RankProto.Persona) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * A name for this person.  Not really used for much of anything now,
       * but helpful to keep in mind who our different personas are so we can
       * talk about them.
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * A name for this person.  Not really used for much of anything now,
       * but helpful to keep in mind who our different personas are so we can
       * talk about them.
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * A name for this person.  Not really used for much of anything now,
       * but helpful to keep in mind who our different personas are so we can
       * talk about them.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * A name for this person.  Not really used for much of anything now,
       * but helpful to keep in mind who our different personas are so we can
       * talk about them.
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * A name for this person.  Not really used for much of anything now,
       * but helpful to keep in mind who our different personas are so we can
       * talk about them.
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * A name for this person.  Not really used for much of anything now,
       * but helpful to keep in mind who our different personas are so we can
       * talk about them.
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string email = 2;
      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 2;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        email_ = value;
        onChanged();
        return this;
      }

      // repeated string good_url = 3;
      private com.google.protobuf.LazyStringList goodUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureGoodUrlIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          goodUrl_ = new com.google.protobuf.LazyStringArrayList(goodUrl_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public java.util.List<java.lang.String>
          getGoodUrlList() {
        return java.util.Collections.unmodifiableList(goodUrl_);
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public int getGoodUrlCount() {
        return goodUrl_.size();
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public java.lang.String getGoodUrl(int index) {
        return goodUrl_.get(index);
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGoodUrlBytes(int index) {
        return goodUrl_.getByteString(index);
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public Builder setGoodUrl(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGoodUrlIsMutable();
        goodUrl_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public Builder addGoodUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGoodUrlIsMutable();
        goodUrl_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public Builder addAllGoodUrl(
          java.lang.Iterable<java.lang.String> values) {
        ensureGoodUrlIsMutable();
        super.addAll(values, goodUrl_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public Builder clearGoodUrl() {
        goodUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string good_url = 3;</code>
       */
      public Builder addGoodUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGoodUrlIsMutable();
        goodUrl_.add(value);
        onChanged();
        return this;
      }

      // repeated string bad_url = 4;
      private com.google.protobuf.LazyStringList badUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureBadUrlIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          badUrl_ = new com.google.protobuf.LazyStringArrayList(badUrl_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public java.util.List<java.lang.String>
          getBadUrlList() {
        return java.util.Collections.unmodifiableList(badUrl_);
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public int getBadUrlCount() {
        return badUrl_.size();
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public java.lang.String getBadUrl(int index) {
        return badUrl_.get(index);
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBadUrlBytes(int index) {
        return badUrl_.getByteString(index);
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public Builder setBadUrl(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBadUrlIsMutable();
        badUrl_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public Builder addBadUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBadUrlIsMutable();
        badUrl_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public Builder addAllBadUrl(
          java.lang.Iterable<java.lang.String> values) {
        ensureBadUrlIsMutable();
        super.addAll(values, badUrl_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public Builder clearBadUrl() {
        badUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string bad_url = 4;</code>
       */
      public Builder addBadUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBadUrlIsMutable();
        badUrl_.add(value);
        onChanged();
        return this;
      }

      // repeated string linked_in_contact_name = 5;
      private com.google.protobuf.LazyStringList linkedInContactName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureLinkedInContactNameIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          linkedInContactName_ = new com.google.protobuf.LazyStringArrayList(linkedInContactName_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string linked_in_contact_name = 5;</code>
       */
      public java.util.List<java.lang.String>
          getLinkedInContactNameList() {
        return java.util.Collections.unmodifiableList(linkedInContactName_);
      }
      /**
       * <code>repeated string linked_in_contact_name = 5;</code>
       */
      public int getLinkedInContactNameCount() {
        return linkedInContactName_.size();
      }
      /**
       * <code>repeated string linked_in_contact_name = 5;</code>
       */
      public java.lang.String getLinkedInContactName(int index) {
        return linkedInContactName_.get(index);
      }
      /**
       * <code>repeated string linked_in_contact_name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getLinkedInContactNameBytes(int index) {
        return linkedInContactName_.getByteString(index);
      }
      /**
       * <code>repeated string linked_in_contact_name = 5;</code>
       */
      public Builder setLinkedInContactName(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLinkedInContactNameIsMutable();
        linkedInContactName_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string linked_in_contact_name = 5;</code>
       */
      public Builder addLinkedInContactName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLinkedInContactNameIsMutable();
        linkedInContactName_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string linked_in_contact_name = 5;</code>
       */
      public Builder addAllLinkedInContactName(
          java.lang.Iterable<java.lang.String> values) {
        ensureLinkedInContactNameIsMutable();
        super.addAll(values, linkedInContactName_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string linked_in_contact_name = 5;</code>
       */
      public Builder clearLinkedInContactName() {
        linkedInContactName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string linked_in_contact_name = 5;</code>
       */
      public Builder addLinkedInContactNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLinkedInContactNameIsMutable();
        linkedInContactName_.add(value);
        onChanged();
        return this;
      }

      // repeated string address_book_contact_name = 6;
      private com.google.protobuf.LazyStringList addressBookContactName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAddressBookContactNameIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          addressBookContactName_ = new com.google.protobuf.LazyStringArrayList(addressBookContactName_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string address_book_contact_name = 6;</code>
       */
      public java.util.List<java.lang.String>
          getAddressBookContactNameList() {
        return java.util.Collections.unmodifiableList(addressBookContactName_);
      }
      /**
       * <code>repeated string address_book_contact_name = 6;</code>
       */
      public int getAddressBookContactNameCount() {
        return addressBookContactName_.size();
      }
      /**
       * <code>repeated string address_book_contact_name = 6;</code>
       */
      public java.lang.String getAddressBookContactName(int index) {
        return addressBookContactName_.get(index);
      }
      /**
       * <code>repeated string address_book_contact_name = 6;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBookContactNameBytes(int index) {
        return addressBookContactName_.getByteString(index);
      }
      /**
       * <code>repeated string address_book_contact_name = 6;</code>
       */
      public Builder setAddressBookContactName(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressBookContactNameIsMutable();
        addressBookContactName_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address_book_contact_name = 6;</code>
       */
      public Builder addAddressBookContactName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressBookContactNameIsMutable();
        addressBookContactName_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address_book_contact_name = 6;</code>
       */
      public Builder addAllAddressBookContactName(
          java.lang.Iterable<java.lang.String> values) {
        ensureAddressBookContactNameIsMutable();
        super.addAll(values, addressBookContactName_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address_book_contact_name = 6;</code>
       */
      public Builder clearAddressBookContactName() {
        addressBookContactName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address_book_contact_name = 6;</code>
       */
      public Builder addAddressBookContactNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressBookContactNameIsMutable();
        addressBookContactName_.add(value);
        onChanged();
        return this;
      }

      // repeated .Interest interest = 7;
      private java.util.List<com.janknspank.proto.UserProto.Interest> interest_ =
        java.util.Collections.emptyList();
      private void ensureInterestIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          interest_ = new java.util.ArrayList<com.janknspank.proto.UserProto.Interest>(interest_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.janknspank.proto.UserProto.Interest, com.janknspank.proto.UserProto.Interest.Builder, com.janknspank.proto.UserProto.InterestOrBuilder> interestBuilder_;

      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public java.util.List<com.janknspank.proto.UserProto.Interest> getInterestList() {
        if (interestBuilder_ == null) {
          return java.util.Collections.unmodifiableList(interest_);
        } else {
          return interestBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public int getInterestCount() {
        if (interestBuilder_ == null) {
          return interest_.size();
        } else {
          return interestBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public com.janknspank.proto.UserProto.Interest getInterest(int index) {
        if (interestBuilder_ == null) {
          return interest_.get(index);
        } else {
          return interestBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public Builder setInterest(
          int index, com.janknspank.proto.UserProto.Interest value) {
        if (interestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInterestIsMutable();
          interest_.set(index, value);
          onChanged();
        } else {
          interestBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public Builder setInterest(
          int index, com.janknspank.proto.UserProto.Interest.Builder builderForValue) {
        if (interestBuilder_ == null) {
          ensureInterestIsMutable();
          interest_.set(index, builderForValue.build());
          onChanged();
        } else {
          interestBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public Builder addInterest(com.janknspank.proto.UserProto.Interest value) {
        if (interestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInterestIsMutable();
          interest_.add(value);
          onChanged();
        } else {
          interestBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public Builder addInterest(
          int index, com.janknspank.proto.UserProto.Interest value) {
        if (interestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInterestIsMutable();
          interest_.add(index, value);
          onChanged();
        } else {
          interestBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public Builder addInterest(
          com.janknspank.proto.UserProto.Interest.Builder builderForValue) {
        if (interestBuilder_ == null) {
          ensureInterestIsMutable();
          interest_.add(builderForValue.build());
          onChanged();
        } else {
          interestBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public Builder addInterest(
          int index, com.janknspank.proto.UserProto.Interest.Builder builderForValue) {
        if (interestBuilder_ == null) {
          ensureInterestIsMutable();
          interest_.add(index, builderForValue.build());
          onChanged();
        } else {
          interestBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public Builder addAllInterest(
          java.lang.Iterable<? extends com.janknspank.proto.UserProto.Interest> values) {
        if (interestBuilder_ == null) {
          ensureInterestIsMutable();
          super.addAll(values, interest_);
          onChanged();
        } else {
          interestBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public Builder clearInterest() {
        if (interestBuilder_ == null) {
          interest_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          interestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public Builder removeInterest(int index) {
        if (interestBuilder_ == null) {
          ensureInterestIsMutable();
          interest_.remove(index);
          onChanged();
        } else {
          interestBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public com.janknspank.proto.UserProto.Interest.Builder getInterestBuilder(
          int index) {
        return getInterestFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public com.janknspank.proto.UserProto.InterestOrBuilder getInterestOrBuilder(
          int index) {
        if (interestBuilder_ == null) {
          return interest_.get(index);  } else {
          return interestBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public java.util.List<? extends com.janknspank.proto.UserProto.InterestOrBuilder> 
           getInterestOrBuilderList() {
        if (interestBuilder_ != null) {
          return interestBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(interest_);
        }
      }
      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public com.janknspank.proto.UserProto.Interest.Builder addInterestBuilder() {
        return getInterestFieldBuilder().addBuilder(
            com.janknspank.proto.UserProto.Interest.getDefaultInstance());
      }
      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public com.janknspank.proto.UserProto.Interest.Builder addInterestBuilder(
          int index) {
        return getInterestFieldBuilder().addBuilder(
            index, com.janknspank.proto.UserProto.Interest.getDefaultInstance());
      }
      /**
       * <code>repeated .Interest interest = 7;</code>
       */
      public java.util.List<com.janknspank.proto.UserProto.Interest.Builder> 
           getInterestBuilderList() {
        return getInterestFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.janknspank.proto.UserProto.Interest, com.janknspank.proto.UserProto.Interest.Builder, com.janknspank.proto.UserProto.InterestOrBuilder> 
          getInterestFieldBuilder() {
        if (interestBuilder_ == null) {
          interestBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.janknspank.proto.UserProto.Interest, com.janknspank.proto.UserProto.Interest.Builder, com.janknspank.proto.UserProto.InterestOrBuilder>(
                  interest_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          interest_ = null;
        }
        return interestBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Persona)
    }

    static {
      defaultInstance = new Persona(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Persona)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Persona_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Persona_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037com/janknspank/proto/rank.proto\032(com/j" +
      "anknspank/database/extensions.proto\032\037com" +
      "/janknspank/proto/user.proto\"\333\001\n\007Persona" +
      "\022\027\n\004name\030\001 \001(\tB\t\210\246\035\001\230\246\035\377\005\022\030\n\005email\030\002 \001(\t" +
      "B\t\210\246\035\001\230\246\035\377\005\022\027\n\010good_url\030\003 \003(\tB\005\230\246\035\377\005\022\026\n\007" +
      "bad_url\030\004 \003(\tB\005\230\246\035\377\005\022%\n\026linked_in_contac" +
      "t_name\030\005 \003(\tB\005\230\246\035\377\005\022(\n\031address_book_cont" +
      "act_name\030\006 \003(\tB\005\230\246\035\377\005\022\033\n\010interest\030\007 \003(\0132" +
      "\t.InterestB!\n\024com.janknspank.protoB\tRank" +
      "Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Persona_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Persona_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Persona_descriptor,
              new java.lang.String[] { "Name", "Email", "GoodUrl", "BadUrl", "LinkedInContactName", "AddressBookContactName", "Interest", });
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registry.add(com.janknspank.database.ExtensionsProto.required);
          registry.add(com.janknspank.database.ExtensionsProto.stringLength);
          registry.add(com.janknspank.database.ExtensionsProto.required);
          registry.add(com.janknspank.database.ExtensionsProto.stringLength);
          registry.add(com.janknspank.database.ExtensionsProto.stringLength);
          registry.add(com.janknspank.database.ExtensionsProto.stringLength);
          registry.add(com.janknspank.database.ExtensionsProto.stringLength);
          registry.add(com.janknspank.database.ExtensionsProto.stringLength);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.janknspank.database.ExtensionsProto.getDescriptor(),
          com.janknspank.proto.UserProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
